"""Output formatters for wiki-mos-audit reports."""
from __future__ import annotations

import json
from dataclasses import asdict

from wiki_mos_audit.models import AuditReport


def format_json_report(
    report: AuditReport,
    suggested_tags: list[str] | None = None,
    added_tags: list[str] | None = None,
    dry_run: bool = False,
    output_file: str | None = None,
) -> str:
    """Format report as JSON string."""
    return json.dumps({
        'title': report.title,
        'score': report.score,
        'issue_count': len(report.issues),
        'issues': [asdict(issue) for issue in report.issues],
        'suggested_maintenance_tags': suggested_tags or [],
        'added_maintenance_tags': added_tags or [],
        'dry_run': dry_run,
        'output_file': output_file,
    }, indent=2)


def format_text_report(report: AuditReport) -> str:
    """Format report as plain text."""
    lines = [f'MOS first-pass audit: {report.title}', f'Score: {report.score}/100', '']
    if not report.issues:
        lines.append('No first-pass MOS issues detected.')
        return '\n'.join(lines)

    for issue in report.issues:
        lines.append(f'- [{issue.severity}] {issue.check_id} ({issue.section})')
        lines.append(f'  {issue.message}')
        lines.append(f'  Evidence: {issue.evidence}')
        lines.append(f'  Fix: {issue.suggestion}')
        lines.append('')

    return '\n'.join(lines).rstrip()


def format_html_report(report: AuditReport) -> str:
    """Format report as a self-contained HTML document."""
    severity_colors = {
        'high': '#dc3545',
        'medium': '#fd7e14',
        'low': '#ffc107',
    }

    issue_rows = []
    for issue in report.issues:
        color = severity_colors.get(issue.severity, '#6c757d')
        msg = _html_escape(issue.message)
        evidence = _html_escape(issue.evidence)
        suggestion = _html_escape(issue.suggestion)
        issue_rows.append(
            f'<tr>'
            f'<td><span style="color:{color};font-weight:bold">{issue.severity.upper()}</span></td>'
            f'<td><code>{issue.check_id}</code></td>'
            f'<td>{issue.section}</td>'
            f'<td>{msg}</td>'
            f'<td><small>{evidence}</small></td>'
            f'<td><small>{suggestion}</small></td>'
            f'</tr>'
        )

    table_html = '\n'.join(issue_rows) if issue_rows else '<tr><td colspan="6">No issues detected.</td></tr>'

    if report.score >= 80:
        bar_color = '#28a745'
    elif report.score >= 50:
        bar_color = '#fd7e14'
    else:
        bar_color = '#dc3545'

    css = (
        'body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;'
        'max-width:960px;margin:2em auto;padding:0 1em;color:#202122}'
        'h1{font-size:1.5em}'
        '.score-bar{background:#eee;border-radius:4px;overflow:hidden;height:24px;margin:1em 0}'
        f'.score-fill{{background:{bar_color};height:100%;line-height:24px;color:white;'
        f'text-align:center;font-size:.85em;font-weight:bold;width:{report.score}%}}'
        'table{border-collapse:collapse;width:100%;margin-top:1em;font-size:.9em}'
        'th,td{border:1px solid #c8ccd1;padding:6px 8px;text-align:left;vertical-align:top}'
        'th{background:#eaecf0}'
        'code{background:#f8f9fa;padding:1px 4px;border-radius:2px;font-size:.9em}'
    )

    return f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>MOS Audit: {_html_escape(report.title)}</title>
<style>{css}</style>
</head>
<body>
<h1>MOS Audit: {_html_escape(report.title)}</h1>
<div class="score-bar"><div class="score-fill">{report.score}/100</div></div>
<p>{len(report.issues)} issue(s) found.</p>
<table>
<thead><tr><th>Severity</th><th>Check</th><th>Section</th><th>Message</th><th>Evidence</th><th>Suggestion</th></tr></thead>
<tbody>
{table_html}
</tbody>
</table>
<footer><p><small>Generated by wiki-mos-audit</small></p></footer>
</body>
</html>'''


def format_batch_summary(reports: list[AuditReport], format: str = 'text') -> str:
    """Format a summary of multiple audit reports."""
    if format == 'json':
        return json.dumps([
            {'title': r.title, 'score': r.score, 'issue_count': len(r.issues)}
            for r in reports
        ], indent=2)

    if format == 'html':
        rows = '\n'.join(
            f'<tr><td>{_html_escape(r.title)}</td><td>{r.score}</td><td>{len(r.issues)}</td></tr>'
            for r in reports
        )
        batch_css = (
            'body{font-family:sans-serif;max-width:800px;margin:2em auto}'
            'table{border-collapse:collapse;width:100%}'
            'th,td{border:1px solid #ccc;padding:6px 8px;text-align:left}'
            'th{background:#eaecf0}'
        )
        return f'''<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>MOS Audit Batch</title>
<style>{batch_css}</style>
</head><body><h1>MOS Audit Batch Summary</h1>
<table><thead><tr><th>Article</th><th>Score</th><th>Issues</th></tr></thead>
<tbody>{rows}</tbody></table></body></html>'''

    # text format
    lines = ['MOS Audit Batch Summary', '=' * 60, '']
    lines.append(f'{"Article":<40} {"Score":>5} {"Issues":>6}')
    lines.append('-' * 60)
    for r in reports:
        truncated = r.title[:38] + '..' if len(r.title) > 40 else r.title
        lines.append(f'{truncated:<40} {r.score:>5} {len(r.issues):>6}')
    lines.append('-' * 60)
    avg = sum(r.score for r in reports) / len(reports) if reports else 0
    lines.append(f'{"Average":<40} {avg:>5.0f} {"":>6}')
    return '\n'.join(lines)


def _html_escape(text: str) -> str:
    """Escape HTML special characters."""
    return text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;')
